name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: 074fc192a0c919a71ee74387d4ded93ddcc75a255bab3de9751409c51ee655cc02-1ed2dc97-a260-4e81-a8e2-1182a419c7090101230034af7110
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"           # no frontend
          api_location: "api"         # points to your Azure Function
          output_location: ""         # no static output
